# Generated by Django 3.2.25 on 2026-01-16 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_choice', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataKey',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('metadata_key', models.CharField(max_length=100, unique=True)),
                ('metadata_description', models.CharField(blank=True, max_length=200)),
                ('metadata_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('date', 'Date'), ('bool', 'Boolean'), ('choice', 'Choice'), ('textarea', 'TextArea'), ('image', 'Image'), ('signature', 'Signature')], max_length=10)),
                ('metadata_choice', models.ManyToManyField(blank=True, to='upload_document_api.MetadataChoice')),
            ],
        ),
        migrations.CreateModel(
            name='UploadDocument',
            fields=[
                ('doc_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='Upload Document ID')),
                ('document', models.FileField(blank=True, max_length=200, null=True, upload_to='uploads/', verbose_name='Document')),
                ('document_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Document name')),
                ('doc_created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ac', 'Active'), ('ia', 'Inactive'), ('de', 'Deleted')], default='ac', max_length=2)),
                ('locked', models.BooleanField(default=False)),
                ('doc_type', models.CharField(choices=[('docx', 'docx'), ('pdf', 'pdf'), ('xlsx', 'xlsx'), ('html', 'html')], default='pdf', max_length=20)),
                ('doc_updated_on', models.DateTimeField(auto_now=True)),
                ('doc_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('doc_group', models.ManyToManyField(blank=True, to='auth.Group')),
                ('notification_list', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataUpload',
            fields=[
                ('meta_upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta_upload_value', models.CharField(max_length=1000)),
                ('meta_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_document_api.metadatakey')),
                ('meta_upload_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_document_api.uploaddocument')),
            ],
        ),
    ]
