# Generated by Django 3.2.25 on 2026-01-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_document_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataupload',
            name='meta_upload_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='upload_document_api.uploaddocument'),
        ),
    ]
